### Creating a new patient record
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "chatpt",
  "email" : "edf@gmail.com" ,
  "address": "123 Main St, Springfield, USA",
  "dateOfBirth": "1990-01-01",
  "registeredDate": "2021-10-01"
}
###